name: Build and Deploy
on:
  push:
    branches: [ master ] # only push events on source branch trigger deployment
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: renzhaosy/hexo-deploy-action@master
        env:
          PERSONAL_TOKEN: ${{ secrets.GH_TOKEN }}
          PUBLISH_REPOSITORY: Yaob1990/Blog # The repository the action should deploy to.
          BRANCH: dist  # The branch the action should deploy to.
          PUBLISH_DIR: ./public # The folder the action should deploy.
