name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to deploy blog.
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true # Checkout private submodules(themes or something else).


      - name: Install dependencies & Generate static files
        run: |
          node -v
          npm i -g hexo-cli
          npm i

      # Deploy hexo blog website.
      - name: Deploy (Hexo g -d)
        id: deploy
        uses: sma11black/hexo-action@v1.0.4
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
      - name: Get the output
        run: |
          echo "${{ steps.deploy.outputs.notify }}"
